[package]
name = "easyiac"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"
toml = "0.9.1"
clap = { version = "4.5", features = ["derive"] }
leeca_proxmox = "0.1.1"
